Repository QuantEcon/lecture-python.myst, pull requests merged in 2025-08, with the labels that each got.

#533 [von_neumann_model] lecture improvements
  lectures/von_neumann_model.md
Labels: content

#557 [FIX] Fix jax and os.fork warnings
  .github/workflows/ci.yml
  lectures/_config.yml
  lectures/back_prop.md
  lectures/status.md
Labels: ready

#566 [likelihood_ratio_processes_2] Update new exercises with learning agents
  lectures/_static/quant-econ.bib
  lectures/likelihood_ratio_process_2.md
Labels: lecture
